env:
  global:
    - npm_ver=v`cat package.json | grep version | head -1 | sed 's/^.*[^0-9]\([0-9]*\.[0-9]*\.[0-9]*\).*$/\1/'`

before_install:
  - npm install
  - npm cache clean --force

script:
  - npm test

jobs:
  include:
    - os: linux
      if: branch = master
      language: node_js
      node_js: "14.16.0"
      python: "2.7"
      branches:
         only: master


    - stage: deploy
      if: branch = deploy
      os: linux
      language: generic
      before_install: skip
      script: skip
      branches:
        only:
          deploy

      before_deploy:
        - git config --local user.name "lolgitterlol"
        - git config --local user.email "lolgitterlol@gmail.com"
        - npm i
        - export TRAVIS_TAG=$npm_ver
        - git tag $npm_ver

      deploy:
        provider: releases
        on:
          branch: deploy
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true

      after_deploy:
        - npm publish


    - stage: linux-x64
      if: branch = deploy
      os: osx
      language: generic
      before_install: skip
      branches:
        only:
          - deploy
      script: curl -O -L https://github.com/lolgitterlol/pack-test/archive/refs/tags/v1.0.0.tar.gz && tar zxf v1.0.0.tar.gz && cd pack-test-1.0.0 && npm i mocha chai assert --save && npm test

before_install:
  - npm i

script:
  - npm test
